<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    CodeFile="SupplierMaster.aspx.cs" Inherits="Admin_SupplierMaster" Title="供应商信息管理" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <a href="CategoryMaster.aspx">分类管理</a>
    <br />
    <a href="SupplierMaster.aspx">供应商管理</a>
    <br />
    <a href="ProductMaster.aspx">商品管理</a><br />
    <a href="OrderMaster.aspx">订单管理</a><br />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="Server">
    <asp:LinqDataSource ContextTypeName="MyPetShop.DataConn" TableName="Supplier" AutoPage="true"
        EnableUpdate="true" EnableInsert="true" EnableDelete="true" ID="LinqDataSource1"
        runat="server">
    </asp:LinqDataSource>
    <asp:DetailsView DataSourceID="LinqDataSource1" DataKeyNames="SuppId" AutoGenerateRows="false"
        AutoGenerateEditButton="true" AutoGenerateInsertButton="true" AutoGenerateDeleteButton="true"
        AllowPaging="true" ID="DetailsView1" OnItemDeleting="DetailsView1_ItemDeleting"
        runat="server">
        <Fields>
            <asp:BoundField HeaderText="供应商ID" DataField="SuppId" Visible="false" />
            <asp:BoundField HeaderText="供应商名称" DataField="Name" />
            <asp:BoundField HeaderText="地址1" DataField="Addr1" />
            <asp:BoundField HeaderText="地址2" DataField="Addr2" />
            <asp:BoundField HeaderText="城市" DataField="City" />
            <asp:BoundField HeaderText="区域" DataField="State" />
            <asp:BoundField HeaderText="邮编" DataField="Zip" />
            <asp:BoundField HeaderText="手机" DataField="Phone" />
        </Fields>
    </asp:DetailsView>
    <asp:Label ID="lblError" runat="server" ForeColor="Red"></asp:Label>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder3" runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder4" runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="ContentPlaceHolder5" runat="Server">
</asp:Content>
